development:
  github_app_id: 35c0e101305f6a030323
  github_app_secret: f0fd4dc09459c66ba016f56d50c2a73651fbd684
  twitter_api_key: Bv41qQ7vlaFJQBEP3ECVPDm3l
  twitter_api_secret: Wr94jEsdah41UMA23gpCGBRzy3pmENuHtXdJxhxocwhLohfYKN

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>