development:
  github_app_id: 35c0e101305f6a030323
  github_app_secret: f0fd4dc09459c66ba016f56d50c2a73651fbd684
  twitter_api_key: Bv41qQ7vlaFJQBEP3ECVPDm3l
  twitter_api_secret: Wr94jEsdah41UMA23gpCGBRzy3pmENuHtXdJxhxocwhLohfYKN

production:
  secret_key_base: 6ffdb4063539fdcade3cefe5a51b76fee81ff525bca0feccaad134f0c4c55fb2ea6578aef7be8770f49c1bb86c5d6fa92f5d029939f8b707061645c26d284a66
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>